# 블로그 기본 설정
title: JS Engineering Notes
description: JS Engineering Notes
baseurl: ""
url: "https://jiseong924.github.io"

# 테마
theme: minima

# 시간대
timezone: Asia/Seoul

# 홈에서 보여줄 글 개수
paginate: 5
paginate_path: "/blog/page:num"

# 메뉴
header:
  pages:
    - home
    - archive
    - about

# 포스트 전역 변수
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

# 마크다운 설정
markdown: kramdown

# 플러그인
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
